### ISSUE TITLE
nohup port-forward unreliable

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/killercoda#24]
The current nohup port-forward command in the operator tutorial is unreliable.

Move this to a user-activated port-forwarding as a `502` at initial startup is not a good look & can lead to the user thinking it's broken and not progressing.

**Comment by beeme1mr** [comment]
Is this an issue with the OFO demo? I've run into issues using port forwarding with the demo app but I have no idea why. Adding an ingress seems to work reliably.

**Comment by agardnerIT** [comment]
I don't think so. Whenever I get the 502 and then re-run the port-forward manually, it works.

I was thinking it's a timing issue (trying to port-forward too early). That's why I put the `sleep 10` in the `intro_foreground.sh` but it still seems flaky.

**Comment by agardnerIT** [comment]
The `nohup` is no longer necessary in my latest trials (see #29). Closing.
