### ISSUE TITLE
Links in open-feature demo are outdated

### ISSUE THREAD

**Issue by aepfli** [open-feature/killercoda#27]
Multiple links within https://github.com/open-feature/killercoda/blob/main/openfeature-demo/step1.md do not exist anymore.

i tried to locate them within the playground but did not find them eg `hex-color.service.ts`

**Comment by agardnerIT** [comment]
Is this it? https://github.com/open-feature/playground/blob/d659a6962008eff33be797a4a900fcd8f4409646/packages/ui/src/app/demos/fib3r/fib3r-demo.tsx#L157
